#!/bin/bash
# =============================================================================
# 26-restore-features.sh  (postgres docker-entrypoint-initdb.d, fresh-boot only)
# =============================================================================
# Makes a clean-slate `docker compose down -v` boot come back with the FULL
# schema: applies the feature migrations 043-053 that are NOT part of the base
# init-scripts (H5 forecasting, News Engine, Analysis, regime gate, multi-asset
# daily, crypto-native, and the SignalBridge admin-approval columns). They are
# idempotent (IF NOT EXISTS), so re-runs are safe.
#
# News/Analysis DATA is NOT restored from a dump — it is re-obtained for real by
# the scrapers (news_daily_pipeline DAG: Investing/Portafolio/LaRepublica/GDELT)
# and regenerated by the analysis pipeline. This script only guarantees the
# tables EXIST so the scrapers have somewhere to write.
#
# Mounted (read-only) by docker-compose.yml on the postgres service:
#   ./database/migrations -> /feature-migrations
#
# Runs during first DB init only. ON_ERROR_STOP is off so one already-applied
# statement or an optional extension (e.g. pgvector 047, intentionally skipped)
# never aborts the rest.
# =============================================================================
set -u
PSQL="psql -v ON_ERROR_STOP=0 --username ${POSTGRES_USER} --dbname ${POSTGRES_DB}"

echo "[26-restore] applying feature migrations 043-053 ..."
if [ -d /feature-migrations ]; then
  for f in $(ls /feature-migrations/04[3-9]_*.sql /feature-migrations/05[0-9]_*.sql 2>/dev/null | sort); do
    case "$f" in
      *047_pgvector*) echo "[26-restore] skip $(basename "$f") (optional pgvector)"; continue ;;
    esac
    echo "[26-restore]   -> $(basename "$f")"
    $PSQL -f "$f" >/dev/null 2>&1 || echo "[26-restore]   warn: $(basename "$f") returned non-zero (may be already applied)"
  done
else
  echo "[26-restore] /feature-migrations not mounted, skipping migrations"
fi

echo "[26-restore] schema ready. News/Analysis data is re-obtained by the real"
echo "[26-restore] scrapers (news_daily_pipeline) + analysis pipeline, not a dump."
echo "[26-restore] done."
