# =============================================================================
# DVC Pipeline Parameters
# =============================================================================
# Central configuration for all DVC pipeline stages.
# Changes to these parameters will trigger re-execution of dependent stages.
#
# Usage:
#   - Modify parameters here
#   - Run `dvc repro` to rebuild affected stages
#   - Use `dvc params diff` to see what changed
#
# Author: Trading Team
# Date: 2026-01-16
# Updated: 2026-01-17 (Added dataset SSOT section)
# =============================================================================

# =============================================================================
# Dataset Configuration
# =============================================================================
# IMPORTANT: For date ranges, see config/date_ranges.yaml (SSOT)
# The date_range section below is DEPRECATED and kept only for backward
# compatibility with older DVC pipelines. New code should use:
#   config/date_ranges.yaml (Python: yaml.safe_load())
#   Or L2 XCom contracts for pipeline stages
dataset:
  # Version identifier
  version: "v2.0.0"
  dvc_tag: "dataset-v2.0.0"

  # Data source
  source: "data/processed/"
  raw_source: "data/raw/"

  # Hash for reproducibility (update when data changes)
  hash: null  # Computed at runtime, logged to MLflow

  # DEPRECATED: Use config/date_ranges.yaml instead
  # These values are kept for backward compatibility only
  # Reference: config/date_ranges.yaml (SSOT)
  date_range:
    # Updated to match date_ranges.yaml (SSOT)
    train_start: "2020-03-01"    # date_ranges.yaml: training.start
    train_end: "2024-12-31"      # date_ranges.yaml: training.end
    validation_start: "2025-01-01"  # date_ranges.yaml: validation.start
    validation_end: "2025-06-30"    # date_ranges.yaml: validation.end
    test_start: "2025-07-01"     # date_ranges.yaml: test.start
    test_end: "2025-12-31"       # date_ranges.yaml: test.end (dynamic)

# =============================================================================
# Data Preparation Parameters
# =============================================================================
prepare:
  # Number of days of historical data to include
  lookback_days: 365

  # Train/validation/test split ratios (must sum to 1.0)
  train_ratio: 0.7
  val_ratio: 0.15
  # test_ratio is implicitly 1 - train_ratio - val_ratio = 0.15

  # Random seed for reproducibility
  random_seed: 42

  # Feature columns to include (from feature_config.json)
  features:
    - log_ret_5m
    - log_ret_1h
    - log_ret_4h
    - rsi_9
    - atr_pct
    - adx_14
    - dxy_z
    - dxy_change_1d
    - vix_z
    - embi_z
    - brent_change_1d
    - rate_spread
    - usdmxn_change_1d

# =============================================================================
# Normalization Parameters
# =============================================================================
normalize:
  # Percentile for clipping outliers (0 = no clipping)
  clip_percentile: 99.5

  # Number of standard deviations for outlier detection
  outlier_std: 4.0

  # Method: zscore, minmax, robust
  method: zscore

# =============================================================================
# Training Parameters - REMOVED (use SSOT)
# =============================================================================
# La seccion 'train:' fue ELIMINADA.
# Use el SSOT centralizado para training:
#
#   from src.config.experiment_loader import get_ppo_hyperparameters
#   hyperparams = get_ppo_hyperparameters()
#
# SSOT: config/experiment_ssot.yaml
# =============================================================================

# =============================================================================
# Evaluation Parameters
# =============================================================================
evaluate:
  # Number of episodes for evaluation
  n_episodes: 100

  # Use deterministic policy (no exploration)
  deterministic: true

  # Metrics to compute
  metrics:
    - sharpe_ratio
    - sortino_ratio
    - max_drawdown
    - win_rate
    - profit_factor
    - total_trades
    - avg_trade_duration

# =============================================================================
# ONNX Export Parameters
# =============================================================================
export:
  # ONNX opset version
  opset_version: 14

  # Optimize for inference
  optimize: true

  # Include metadata
  include_metadata: true

# =============================================================================
# Backtest Parameters
# =============================================================================
backtest:
  # Initial capital
  initial_balance: 10000

  # Transaction costs (basis points)
  transaction_cost_bps: 75

  # Slippage (basis points)
  slippage_bps: 15

  # Position sizing
  position_size: 1.0
  max_position: 1.0

  # Risk limits
  max_daily_loss: -0.02
  max_drawdown: -0.15

  # Signal thresholds (SSOT: experiment_ssot.yaml)
  long_threshold: 0.50
  short_threshold: -0.50

  # Trading hours (UTC)
  trading_start_hour: 13
  trading_end_hour: 17
  trading_end_minute: 55

# =============================================================================
# Model Promotion Thresholds
# =============================================================================
promotion:
  # Staging promotion requirements
  staging:
    min_sharpe_ratio: 0.5
    min_win_rate: 0.45
    max_drawdown: -0.15
    min_trades: 50

  # Production promotion requirements
  production:
    min_sharpe_ratio: 1.0
    min_win_rate: 0.50
    max_drawdown: -0.10
    min_trades: 100
    min_staging_days: 7

# =============================================================================
# MLflow Configuration
# =============================================================================
mlflow:
  tracking_uri: http://localhost:5000
  registry_uri: http://localhost:5000
  artifact_location: s3://mlflow-artifacts/

  # Experiment tags
  tags:
    project: usdcop-trading
    team: algo-trading
    environment: development

# =============================================================================
# DVC Remote Configuration
# =============================================================================
dvc:
  remote:
    name: minio
    url: s3://dvc-storage
    endpointurl: http://localhost:9000

  # Cache settings
  cache:
    type: symlink
    dir: .dvc/cache

# =============================================================================
# Logging Configuration
# =============================================================================
logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/training.log

# =============================================================================
# Forecasting Pipeline Configuration
# =============================================================================
# SSOT for daily USDCOP forecasting models.
# Python SSOT: src/forecasting/config.py
# Data Contracts: src/forecasting/data_contracts.py
forecasting:
  # Version identifier
  version: "1.0.0"

  # Data configuration
  data:
    train_start: "2020-01-01"
    train_end: "2024-12-31"
    validation_start: "2025-01-01"
    validation_end: "2025-06-30"
    test_start: "2025-07-01"
    test_end: "2025-12-31"
    # Minimum days for feature calculation (MA50 needs 50)
    lookback_days: 50
    # Data quality thresholds
    min_records: 500
    max_null_pct: 5.0

  # Feature configuration (19 SSOT features)
  features:
    # Number of features (validated by data_contracts.py)
    num_features: 19
    # Target horizons (days ahead)
    target_horizons: [1, 5, 10, 15, 20, 25, 30]
    # RSI period
    rsi_period: 14
    # MA periods
    ma_short_period: 20
    ma_long_period: 50

  # Training configuration
  training:
    # Walk-forward validation windows
    walk_forward_windows: 5
    min_train_size: 252
    expansion_step: 63
    # Random seed
    random_seed: 42
    # MLflow experiment
    experiment_name: "forecasting-training"
    # Model list (9 models from contracts.py)
    models:
      - xgboost
      - lightgbm
      - catboost
      - hybrid_xgboost
      - hybrid_lightgbm
      - hybrid_catboost
      - ridge
      - bayesian_ridge
      - ard
    # Boosting defaults
    boosting:
      n_estimators: 500
      max_depth: 6
      learning_rate: 0.03
      subsample: 0.8
      colsample_bytree: 0.8
      early_stopping_rounds: 50

  # Inference configuration
  inference:
    generate_ensembles: true
    persist_to_db: true
    upload_images: true

  # Storage paths
  storage:
    models_bucket: "forecasting-models"
    forecasts_bucket: "forecasts"
    datasets_bucket: "forecasting-datasets"
    # Database tables
    ohlcv_table: "bi.dim_daily_usdcop"
    features_view: "bi.v_forecasting_features"
    forecasts_table: "bi.fact_forecasts"

  # Promotion thresholds (Direction Accuracy %)
  promotion:
    staging:
      min_da: 52.0
    production:
      min_da: 55.0
      min_staging_days: 7

  # MLflow configuration
  mlflow:
    enabled: true
    tracking_uri: ${MLFLOW_TRACKING_URI:-http://localhost:5000}
    experiment_name: "forecasting-training"
    # Registry configuration
    registry:
      enabled: true
      model_name_prefix: "forecasting"
    # Logging configuration
    logging:
      log_models: true
      log_artifacts: true
      log_params: true
      log_metrics: true
    # Tags
    tags:
      project: "usdcop-forecasting"
      team: "algo-trading"
      pipeline: "forecasting"
