# Prometheus Alert Rules for USDCOP RL Trading System

groups:
  # Trading System Health Alerts
  - name: trading_system_health
    rules:
      - alert: TradingDashboardDown
        expr: up{job="trading-dashboard"} == 0
        for: 1m
        labels:
          severity: critical
          service: frontend
        annotations:
          summary: "Trading Dashboard is down"
          description: "The trading dashboard has been down for more than 1 minute."

      - alert: BackendAPIDown
        expr: up{job="backend-api"} == 0
        for: 1m
        labels:
          severity: critical
          service: backend
        annotations:
          summary: "Backend API is down"
          description: "The backend API has been down for more than 1 minute."

      - alert: DatabaseConnectionFailure
        expr: up{job="postgres"} == 0
        for: 2m
        labels:
          severity: critical
          service: database
        annotations:
          summary: "PostgreSQL database is down"
          description: "PostgreSQL has been down for more than 2 minutes."

  # Performance Alerts
  - name: performance_alerts
    rules:
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2.0
        for: 5m
        labels:
          severity: warning
          service: performance
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is above 2 seconds for more than 5 minutes."

      - alert: HighCPUUsage
        expr: rate(container_cpu_usage_seconds_total[5m]) * 100 > 80
        for: 10m
        labels:
          severity: warning
          service: performance
        annotations:
          summary: "High CPU usage"
          description: "CPU usage is above 80% for more than 10 minutes."

      - alert: HighMemoryUsage
        expr: (container_memory_usage_bytes / container_spec_memory_limit_bytes) * 100 > 85
        for: 10m
        labels:
          severity: warning
          service: performance
        annotations:
          summary: "High memory usage"
          description: "Memory usage is above 85% for more than 10 minutes."

  # Trading Model Alerts
  - name: trading_model_alerts
    rules:
      - alert: ModelPredictionAccuracyLow
        expr: model_prediction_accuracy < 0.70
        for: 15m
        labels:
          severity: warning
          service: ml_model
        annotations:
          summary: "Model prediction accuracy is low"
          description: "Model prediction accuracy has been below 70% for more than 15 minutes."

      - alert: ModelTrainingFailed
        expr: increase(model_training_failures_total[1h]) > 3
        for: 1m
        labels:
          severity: critical
          service: ml_model
        annotations:
          summary: "Multiple model training failures"
          description: "More than 3 model training failures in the last hour."

      - alert: RLActionDistributionAnomaly
        expr: abs(rl_action_distribution_sell - rl_action_distribution_buy) > 0.8
        for: 30m
        labels:
          severity: warning
          service: ml_model
        annotations:
          summary: "RL action distribution anomaly detected"
          description: "Extreme bias in RL action distribution detected for more than 30 minutes."

  # Risk Management Alerts
  - name: risk_management_alerts
    rules:
      - alert: VaRThresholdExceeded
        expr: var_95_1_day_percentage > 0.10
        for: 5m
        labels:
          severity: critical
          service: risk_management
        annotations:
          summary: "VaR threshold exceeded"
          description: "1-day VaR at 95% confidence exceeds 10% of portfolio value."

      - alert: StressTestFailure
        expr: stress_test_pass_rate < 0.80
        for: 1m
        labels:
          severity: warning
          service: risk_management
        annotations:
          summary: "Multiple stress tests failing"
          description: "Less than 80% of stress tests are passing."

      - alert: HighLeverage
        expr: current_leverage > 2.8
        for: 10m
        labels:
          severity: warning
          service: risk_management
        annotations:
          summary: "High leverage detected"
          description: "Current leverage exceeds 2.8x for more than 10 minutes."

  # Data Pipeline Alerts
  - name: data_pipeline_alerts
    rules:
      - alert: DataPipelineQualityGateFailed
        expr: pipeline_quality_gate_status == 0
        for: 5m
        labels:
          severity: critical
          service: data_pipeline
        annotations:
          summary: "Data pipeline quality gate failed"
          description: "One or more data pipeline quality gates have failed."

      - alert: DataLeakageDetected
        expr: data_leakage_score > 0.05
        for: 1m
        labels:
          severity: critical
          service: data_pipeline
        annotations:
          summary: "Data leakage detected"
          description: "Potential data leakage detected in the pipeline."

      - alert: DataFreshnessIssue
        expr: (time() - data_last_updated_timestamp) > 1800
        for: 5m
        labels:
          severity: warning
          service: data_pipeline
        annotations:
          summary: "Data freshness issue"
          description: "Data has not been updated for more than 30 minutes."

      - alert: AirflowDAGFailure
        expr: increase(airflow_dag_failures_total[1h]) > 2
        for: 1m
        labels:
          severity: critical
          service: data_pipeline
        annotations:
          summary: "Multiple Airflow DAG failures"
          description: "More than 2 DAG failures in the last hour."

  # Storage and Infrastructure Alerts
  - name: infrastructure_alerts
    rules:
      - alert: DiskSpaceRunningLow
        expr: (node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100 < 15
        for: 5m
        labels:
          severity: warning
          service: infrastructure
        annotations:
          summary: "Disk space running low"
          description: "Available disk space is below 15%."

      - alert: RedisConnectionFailure
        expr: up{job="redis"} == 0
        for: 2m
        labels:
          severity: critical
          service: infrastructure
        annotations:
          summary: "Redis is down"
          description: "Redis has been down for more than 2 minutes."

      - alert: MinIOStorageIssue
        expr: up{job="minio"} == 0
        for: 2m
        labels:
          severity: critical
          service: infrastructure
        annotations:
          summary: "MinIO storage is down"
          description: "MinIO storage service has been down for more than 2 minutes."

      - alert: InfluxDBDown
        expr: up{job="influxdb"} == 0
        for: 2m
        labels:
          severity: warning
          service: infrastructure
        annotations:
          summary: "InfluxDB is down"
          description: "InfluxDB time series database has been down for more than 2 minutes."

  # Security and Compliance Alerts
  - name: security_compliance_alerts
    rules:
      - alert: UnauthorizedAPIAccess
        expr: rate(http_requests_total{status=~"401|403"}[5m]) > 10
        for: 2m
        labels:
          severity: warning
          service: security
        annotations:
          summary: "High rate of unauthorized API access attempts"
          description: "More than 10 unauthorized access attempts per second for 2 minutes."

      - alert: ComplianceCheckFailure
        expr: compliance_check_status == 0
        for: 1m
        labels:
          severity: critical
          service: compliance
        annotations:
          summary: "Compliance check failed"
          description: "One or more compliance checks have failed."

      - alert: SecurityVulnerabilityDetected
        expr: security_vulnerability_count > 0
        for: 1m
        labels:
          severity: critical
          service: security
        annotations:
          summary: "Security vulnerability detected"
          description: "Critical security vulnerabilities have been detected."

  # Trading Performance Alerts
  - name: trading_performance_alerts
    rules:
      - alert: LowSortinoRatio
        expr: sortino_ratio_current < 1.5
        for: 30m
        labels:
          severity: warning
          service: trading_performance
        annotations:
          summary: "Low Sortino ratio"
          description: "Sortino ratio has been below 1.5 for more than 30 minutes."

      - alert: DailyPnLAlert
        expr: abs(daily_pnl_percentage) > 0.05
        for: 1m
        labels:
          severity: warning
          service: trading_performance
        annotations:
          summary: "High daily PnL volatility"
          description: "Daily PnL exceeded 5% threshold."

      - alert: TradingVolumeAnomaly
        expr: (trading_volume_current / trading_volume_average_7d) < 0.1 or (trading_volume_current / trading_volume_average_7d) > 10
        for: 15m
        labels:
          severity: warning
          service: trading_performance
        annotations:
          summary: "Trading volume anomaly"
          description: "Trading volume is significantly different from 7-day average."