global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'trading-app'
    static_configs:
      - targets: ['trading-app:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'trading-dashboard'
    static_configs:
      - targets: ['trading-dashboard:8050']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']
    scrape_interval: 30s

  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    scrape_interval: 30s

  - job_name: 'airflow'
    static_configs:
      - targets: ['airflow-webserver:8080']
    scrape_interval: 30s