# USDCOP Market Configuration
market:
  name: "USDCOP"
  type: "forex"
  base_currency: "USD"
  quote_currency: "COP"
  
  trading_hours:
    open: "00:00"
    close: "23:59"
    timezone: "UTC"
    days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
    
  volatility_profile:
    typical_daily_range: 0.02  # 2% daily range
    max_daily_range: 0.05      # 5% max daily range
    overnight_gap_risk: 0.01   # 1% overnight gap risk
    
  risk_parameters:
    initial_balance: 10000
    max_position_size: 1.0
    max_daily_loss: 0.05      # 5% max daily loss
    max_drawdown: 0.15        # 15% max drawdown
    
  execution:
    commission_rate: 0.001     # 0.1% commission
    slippage_rate: 0.0001     # 0.01% slippage
    min_trade_size: 0.01      # Minimum lot size
    max_trade_size: 10.0      # Maximum lot size
    
  technical_indicators:
    rsi:
      periods: [14, 21, 28]
      overbought: 70
      oversold: 30
      
    macd:
      fast_period: 12
      slow_period: 26
      signal_period: 9
      
    bollinger_bands:
      periods: [20, 30]
      std_dev: [2, 3]
      
    atr:
      periods: [14, 21]
      
    stochastic:
      k_period: 14
      d_period: 3
      overbought: 80
      oversold: 20
      
  features:
    price_features: true
    volume_features: true
    technical_features: true
    temporal_features: true
    volatility_features: true
    pattern_features: true
    
  reinforcement_learning:
    state_space:
      price_features: 10
      technical_features: 15
      temporal_features: 5
      total_features: 30
      
    action_space:
      actions: ["BUY", "SELL", "HOLD"]
      position_sizing: [0.1, 0.25, 0.5, 0.75, 1.0]
      
    reward_function:
      profit_factor: 1.0
      drawdown_penalty: -2.0
      holding_penalty: -0.001
      transaction_cost_penalty: -0.5
      
    training:
      episodes: 1000
      max_steps_per_episode: 1000
      learning_rate: 0.001
      batch_size: 32
      memory_size: 10000
      gamma: 0.99
      epsilon: 0.1
