#!/usr/bin/env python3
"""Retroactively log H5 Smart Simple training artifacts to MLflow.

Reads existing JSON artifacts generated by
``scripts/train_and_export_smart_simple.py`` and creates MLflow runs for
them. Idempotent: skips runs that already exist (matched by ``run_name``
within the experiment).

Usage:
    python scripts/log_training_to_mlflow.py            # log all found artifacts
    python scripts/log_training_to_mlflow.py --dry-run  # preview only, no MLflow calls

Environment:
    MLFLOW_TRACKING_URI  — tracking server URI (default: http://localhost:5001)

Contract:
    * Non-destructive: read-only on training artifacts.
    * Self-contained: no imports from project ``src/`` tree.
    * Safe: fails fast with clear guidance if MLflow server unreachable.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import sys
from pathlib import Path
from typing import Any, Optional

# Root of the repository. The script is expected to live in ``scripts/``.
REPO_ROOT = Path(__file__).resolve().parent.parent
PRODUCTION_DIR = REPO_ROOT / "usdcop-trading-dashboard" / "public" / "data" / "production"
TRADES_DIR = PRODUCTION_DIR / "trades"

EXPERIMENT_NAME = "h5_smart_simple_v2"
DEFAULT_TRACKING_URI = "http://localhost:5001"

logger = logging.getLogger("mlflow_logger")


# ---------------------------------------------------------------------------
# Artifact discovery & normalisation
# ---------------------------------------------------------------------------


def _safe_load_json(path: Path) -> Optional[dict[str, Any]]:
    """Load JSON file or return None with a warning."""
    if not path.exists():
        logger.warning("Artifact not found, skipping: %s", path)
        return None
    try:
        with path.open("r", encoding="utf-8") as handle:
            return json.load(handle)
    except json.JSONDecodeError as exc:
        logger.warning("Failed to parse JSON %s: %s", path, exc)
        return None


def _extract_metrics(summary: dict[str, Any]) -> dict[str, float]:
    """Pull scalar metrics out of a summary.json-style payload."""
    strategy_id = summary.get("strategy_id")
    strategies = summary.get("strategies", {}) or {}
    active = strategies.get(strategy_id, {}) if strategy_id else {}

    stats = summary.get("statistical_tests", {}) or {}

    candidates: dict[str, Any] = {
        "total_return_pct": active.get("total_return_pct"),
        "sharpe": active.get("sharpe"),
        "max_dd_pct": active.get("max_dd_pct"),
        "win_rate_pct": active.get("win_rate_pct"),
        "profit_factor": active.get("profit_factor"),
        "final_equity": active.get("final_equity"),
        "trading_days": active.get("trading_days"),
        "n_long": active.get("n_long"),
        "n_short": active.get("n_short"),
        "direction_accuracy_pct": summary.get("direction_accuracy_pct"),
        "p_value": stats.get("p_value"),
        "n_trading_days": summary.get("n_trading_days"),
    }

    # Derive trade count from exit_reasons map when present.
    exit_reasons = active.get("exit_reasons") or {}
    if isinstance(exit_reasons, dict) and exit_reasons:
        candidates["trades"] = sum(
            int(v) for v in exit_reasons.values() if isinstance(v, (int, float))
        )

    metrics: dict[str, float] = {}
    for key, value in candidates.items():
        if value is None:
            continue
        try:
            metrics[key] = float(value)
        except (TypeError, ValueError):
            continue
    return metrics


def _build_artifact_record(
    summary_path: Path,
    phase: str,
    trades_filename: Optional[str],
) -> Optional[dict[str, Any]]:
    """Assemble everything needed to log a single run."""
    summary = _safe_load_json(summary_path)
    if summary is None:
        return None

    strategy_id = summary.get("strategy_id", "smart_simple_v11")
    year = summary.get("year")
    if year is None:
        logger.warning("Summary %s missing 'year', skipping", summary_path)
        return None

    run_name = f"{strategy_id}_{year}_{phase}"
    metrics = _extract_metrics(summary)

    extra_artifacts: list[Path] = []
    if trades_filename:
        trades_path = TRADES_DIR / trades_filename
        if trades_path.exists():
            extra_artifacts.append(trades_path)
        else:
            logger.warning("Trades file missing, skipping artifact: %s", trades_path)

    approval_path = PRODUCTION_DIR / "approval_state.json"
    if approval_path.exists():
        extra_artifacts.append(approval_path)

    return {
        "run_name": run_name,
        "strategy_id": strategy_id,
        "year": int(year),
        "phase": phase,
        "summary_path": summary_path,
        "extra_artifacts": extra_artifacts,
        "metrics": metrics,
        "summary": summary,
    }


def discover_artifacts() -> list[dict[str, Any]]:
    """Return one record per logical training run we can find."""
    records: list[dict[str, Any]] = []

    backtest = _build_artifact_record(
        PRODUCTION_DIR / "summary_2025.json",
        phase="backtest",
        trades_filename="smart_simple_v11_2025.json",
    )
    if backtest:
        records.append(backtest)

    production = _build_artifact_record(
        PRODUCTION_DIR / "summary.json",
        phase="production",
        trades_filename="smart_simple_v11.json",
    )
    if production:
        records.append(production)

    return records


# ---------------------------------------------------------------------------
# MLflow interaction
# ---------------------------------------------------------------------------


def _ensure_mlflow_reachable(tracking_uri: str) -> Any:
    """Import mlflow, point it at the server, and verify connectivity."""
    try:
        import mlflow  # type: ignore[import-not-found]
    except ImportError:
        logger.error(
            "mlflow is not installed. Install with: pip install mlflow  "
            "(or: pip install -e '.[all]')"
        )
        sys.exit(1)

    mlflow.set_tracking_uri(tracking_uri)
    try:
        # Any lightweight call that hits the backend will surface a
        # connection error if the server is down.
        mlflow.search_experiments(max_results=1)
    except Exception as exc:  # noqa: BLE001 - broad by design
        logger.error("MLflow server unreachable at %s: %s", tracking_uri, exc)
        logger.error("Start MLflow first: docker compose up -d mlflow")
        sys.exit(1)
    return mlflow


def _run_name_exists(mlflow: Any, experiment_id: str, run_name: str) -> bool:
    """Check whether an MLflow run with this name already exists."""
    query = f"tags.mlflow.runName = '{run_name}'"
    existing = mlflow.search_runs(
        experiment_ids=[experiment_id],
        filter_string=query,
        max_results=1,
        output_format="list",
    )
    return bool(existing)


def log_record(mlflow: Any, experiment_id: str, record: dict[str, Any]) -> bool:
    """Log a single record to MLflow. Returns True if a new run was created."""
    run_name: str = record["run_name"]

    if _run_name_exists(mlflow, experiment_id, run_name):
        logger.info("Run already exists, skipping: %s", run_name)
        return False

    params = {
        "strategy": "smart_simple_v11",
        "phase": record["phase"],
        "year": record["year"],
        "model_ensemble": "ridge+bayesian_ridge+xgboost",
        "regime_gate": True,
        "dynamic_leverage": True,
    }

    with mlflow.start_run(run_name=run_name, experiment_id=experiment_id):
        mlflow.set_tag("course", "mlops_final_project")
        mlflow.set_tag("strategy_id", record["strategy_id"])
        mlflow.set_tag("phase", record["phase"])

        mlflow.log_params(params)

        metrics = record["metrics"]
        if metrics:
            mlflow.log_metrics(metrics)
            logger.info("Logged %d metrics for %s", len(metrics), run_name)
        else:
            logger.warning("No metrics extracted for %s", run_name)

        summary_path: Path = record["summary_path"]
        mlflow.log_artifact(str(summary_path))
        for extra in record["extra_artifacts"]:
            mlflow.log_artifact(str(extra))

    logger.info("Created MLflow run: %s", run_name)
    return True


# ---------------------------------------------------------------------------
# Dry-run reporting
# ---------------------------------------------------------------------------


def _print_dry_run(records: list[dict[str, Any]]) -> None:
    """Emit a human-readable summary of what the real run would do."""
    if not records:
        logger.info("Dry run: no artifacts discovered, nothing to log")
        return

    logger.info("Dry run: %d run(s) would be considered", len(records))
    for record in records:
        logger.info("  run_name=%s", record["run_name"])
        logger.info("    phase=%s year=%s", record["phase"], record["year"])
        logger.info("    summary=%s", record["summary_path"].relative_to(REPO_ROOT))
        for extra in record["extra_artifacts"]:
            logger.info("    artifact=%s", extra.relative_to(REPO_ROOT))
        if record["metrics"]:
            preview = ", ".join(
                f"{k}={v:.4g}" for k, v in sorted(record["metrics"].items())
            )
            logger.info("    metrics=%s", preview)
        else:
            logger.info("    metrics=<none>")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Log existing H5 Smart Simple training artifacts to MLflow "
        "(idempotent, non-destructive).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print what would be logged without touching MLflow.",
    )
    parser.add_argument(
        "--tracking-uri",
        default=os.environ.get("MLFLOW_TRACKING_URI", DEFAULT_TRACKING_URI),
        help="MLflow tracking server URI. Defaults to $MLFLOW_TRACKING_URI or "
        f"{DEFAULT_TRACKING_URI}.",
    )
    parser.add_argument(
        "--experiment-name",
        default=EXPERIMENT_NAME,
        help=f"MLflow experiment name (default: {EXPERIMENT_NAME}).",
    )
    return parser.parse_args(argv)


def main(argv: Optional[list[str]] = None) -> int:
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        datefmt="%Y-%m-%d %H:%M:%S",
    )

    args = _parse_args(argv)

    records = discover_artifacts()
    if not records:
        logger.warning("No training artifacts found under %s", PRODUCTION_DIR)
        return 0

    if args.dry_run:
        _print_dry_run(records)
        return 0

    mlflow = _ensure_mlflow_reachable(args.tracking_uri)
    logger.info("Using MLflow tracking URI: %s", args.tracking_uri)

    experiment = mlflow.set_experiment(args.experiment_name)
    experiment_id = getattr(experiment, "experiment_id", None) or str(experiment)
    logger.info(
        "Experiment: %s (id=%s)", args.experiment_name, experiment_id
    )

    created = 0
    for record in records:
        try:
            if log_record(mlflow, experiment_id, record):
                created += 1
        except Exception as exc:  # noqa: BLE001 - don't abort full run on one failure
            logger.error("Failed to log %s: %s", record["run_name"], exc)

    logger.info(
        "Done. %d new run(s) created, %d skipped (already existed).",
        created,
        len(records) - created,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
